# Custom Language File for Launcher Customizer

[ejs.app]
title = "HotBrain Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Vigovskiy/HotBrain-MC-Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/up6SZeKm59"

[ejs.settings]
sourceGithubLink = "https://github.com/Vigovskiy/HotBrain-MC-Launcher"
supportLink = "https://github.com/Vigovskiy/HotBrain-MC-Launcher/issues"

[ejs.welcome]
welcomeHeader = "ДОБРО ПОЖАЛОВАТЬ В HOTBRAIN"
welcomeDescription = "Этот лаунчер создан для того, чтобы объединить единомышленников и людей, близких по духу. Здесь вы найдёте сервер с уютной атмосферой и дружелюбным сообществом. Мы стараемся поддерживать порядок и помогать каждому игроку. Администрация всегда на связи и открыта к диалогу. У нас нет места токсичности и грубости — только уважение и комфорт. Сервер постоянно обновляется и развивается вместе с игроками. Ты можешь просто зайти и играть в своё удовольствие. Будь то строительство, выживание или общение — место найдётся всем. Мы ценим активность и хорошее настроение."
welcomeDescCTA = "Присоединяйся — здесь тебе точно понравится."
